name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build essentials
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Configure build
        run: cmake C:/Users/User/source/repos/PowerToys/deps/spdlog/tests

      - name: Build project
        run: cmake --build .

      - name: Run tests
        run: ctest
