name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up compiler
        uses: actions/setup-cpp@v2
        with:
          compiler: clang # or g++, depending on your project

      - name: Configure build
        run: cmake .

      - name: Build project
        run: cmake --build .

      - name: Run tests
        run: ctest
