name: Build and Test PowerToys

on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install MSVC Build Tools
        run: |
          # Download and install MSVC Build Tools silently
          Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_buildtools.exe" -OutFile vs_buildtools.exe
          Start-Process -Wait -FilePath .\vs_buildtools.exe -ArgumentList '--quiet --norestart --wait --installPath C:\BuildTools --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.ATLMFC --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64'
      
      - name: Install dependencies
        run: |
          # Install CMake using Chocolatey
          choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"'
      
      - name: Configure build
        run: |
          mkdir build
          cd build
          cmake ..
      
      - name: Build PowerToys
        run: cmake --build build
      
      - name: Run tests
        run: |
          cd build
          ctest
