name: Build and Test PowerToys

on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: PowerToys  # Set the working directory
        run: |
          # Install CMake using Chocolatey
          choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"'
      
      - name: Configure build
        working-directory: PowerToys/build  # Set the working directory
        run: |
          cmake ..
      
      - name: Build PowerToys
        working-directory: PowerToys/build  # Set the working directory
        run: cmake --build .
      
      - name: Run tests
        working-directory: PowerToys/build  # Set the working directory
        run: ctest
