name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build essentials
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Run Tests
        run: |
          if [ -d "PowerToys/deps/spdlog/tests" ]; then
            cd PowerToys/deps/spdlog/tests
            mkdir build
            cd build
            cmake ..
            cmake --build .
            ctest
          else
            echo "Tests directory not found, skipping tests."
          fi

      - name: Deploy if Tests Passed
        if: ${{ job.status == 'success' }}
        run: |
          if [ -f "PowerToysInstaller.exe" ]; then
            echo "Deploying PowerToysInstaller.exe..."
            # Add your deployment commands here
          else
            echo "PowerToysInstaller.exe not found, skipping deployment."
          fi
