name: Build and Test PowerToys

on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Install CMake using Chocolatey
          choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"'
      
      - name: Configure build
        run: |
          # Navigate to the correct directory containing CMakeLists.txt
          cd PowerToys
      
          # Create build directory and configure build
          mkdir build
          cd build
          cmake ..
      
      - name: Build PowerToys
        run: cmake --build build
      
      - name: Run tests
        run: |
          cd build
          ctest
